export {default as Banner} from './banner.png';
export {default as Product1} from './pr1.png';
export {default as Product2} from './pr2.png';
export {default as Product3} from './pr3.png';
export {default as Product4} from './pr4.png';
export {default as Product5} from './pr5.png';
export {default as NotitedLogo} from './notied-logo.png';
export {default as OilFilter} from './oil-filter.png';
export {default as OxiFilter} from './oxi-filter.png';